# ????
spring.application.name=hello-server

# MySQL ?????
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/hello_server?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456

# ===================== Redis ?????7???=====================
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.database=0
spring.data.redis.timeout=10s

# MyBatis-Plus ??
mybatis-plus.mapper-locations=classpath:mapper/*.xml
mybatis-plus.type-aliases-package=com.y212318155.helloserver.entity
mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# ????
logging.level.org.springframework.web=INFO
logging.level.com.y212318155.helloserver.mapper=DEBUG

# JWT ??
jwt.secret=ThisIsMySecretKeyForJwtToken1234567890123456
jwt.expiration=86400000